version: '3.9'

services:
  database:
    image: postgres:latest
    restart: always
    ports:
      - "0.0.0.0:5432:8080"
    volumes:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASS}
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${DATABASE_NAME}", "-U", "${DATABASE_USER}" ]
      interval: 10s
      timeout: 10s
      retries: 5
  
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    command: >
      bash -c "python manage.py migrate --noinput;
      python manage.py flush --noinput; 
      PGPASSWORD=${DATABASE_PASS} psql -h database -U ${DATABASE_USER} -d ${DATABASE_NAME} -W -f data.sql;
      python manage.py runserver 0.0.0.0:8080"
    volumes:
      - .:/code
    ports:
      - "0.0.0.0:8080:8080"
    depends_on:
      database:
        condition: service_healthy

  tests:
    image: mrexpen/planet_olymp_phase2
    pull_policy: always
    ports:
      - "0.0.0.0:8090:8080"
    depends_on:
      - webapi
    environment:
      SERVER_URL: http://webapi:8080
      STAGE: all