version: '3.9'

services:
  database:
    image: postgres:14
    restart: always
    volumes:
      - ./dump:/var/lib/postgresql/data
#      - ./:/root/db
    environment:
      - POSTGRES_DB=animals
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    ports:
      - "0.0.0.0:5432:8080"

  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    command: >
      bash -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8080"
    volumes:
      - .:/code
    ports:
      - "0.0.0.0:8080:8080"
    depends_on:
      - database

  tests:
    image: mrexpen/planet_olymp_phase1
    pull_policy: always
    ports:
      - "0.0.0.0:8090:8080"
    depends_on:
      - webapi
    environment:
      SERVER_URL: http://webapi:8080
      STAGE: 2
      # all - запуск всех тестов из трёх доступных этапов
      # 0, 1 или 2 - запуск тестов для соответствующего этапа