version: '3.9'

services:
  database:
    image: nouchka/sqlite3:latest
    volumes:
      - ./:/root/db
    environment:
      - SQLITE3_DB=db.sqlite3

  webapi:
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/code
    ports:
      - "0.0.0.0:8080:8080"
    depends_on:
      - database

  tests:
    image: mrexpen/planet_olymp_phase1
    pull_policy: always
    ports:
      - "0.0.0.0:8090:8080"
    depends_on:
      - webapi
    environment:
      SERVER_URL: http://webapi:8080
      STAGE: all
      # all - запуск всех тестов из трёх доступных этапов
      # 0, 1 или 2 - запуск тестов для соответствующего этапа
