# Generated by Django 4.1.7 on 2023-02-17 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_account_delete_example'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['id']},
        ),
    ]
