# Generated by Django 4.1.7 on 2023-02-17 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_animaltype'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTimeOfVisitLocationPoint', models.DateTimeField()),
                ('locationPointId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.location')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
