# Generated by Django 4.1.7 on 2023-02-17 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_animallocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('length', models.FloatField()),
                ('height', models.FloatField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=15)),
                ('lifeStatus', models.CharField(blank=True, choices=[('A', 'Alive'), ('D', 'Dead')], default='A', max_length=10)),
                ('chippingDateTime', models.DateTimeField(auto_now_add=True)),
                ('deathDateTime', models.DateTimeField(blank=True, default=None)),
                ('animalTypes', models.ManyToManyField(to='main.animaltype')),
                ('chipperID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.account')),
                ('chippingLocationId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.location')),
                ('visitedLocations', models.ManyToManyField(to='main.animallocation')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
