# Generated by Django 4.1.7 on 2023-02-17 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_animal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='deathDateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
