# Generated by Django 4.1.7 on 2023-02-18 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_animal_deathdatetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='chipperID',
            new_name='chipperId',
        ),
    ]
