# Generated by Django 4.1.7 on 2023-02-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_chipperid_animal_chipperid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHER', 'OTHER')], max_length=15),
        ),
        migrations.AlterField(
            model_name='animal',
            name='lifeStatus',
            field=models.CharField(blank=True, choices=[('ALIVE', 'ALIVE'), ('DEAD', 'DEAD')], default='ALIVE', max_length=10),
        ),
    ]
