# Generated by Django 4.1.7 on 2023-04-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_animallocation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'ADMIN'), ('CHIPPER', 'CHIPPER'), ('USER', 'USER')], default='USER', max_length=10),
        ),
    ]
